/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define(['csui/lib/jquery.mockjax'], function (mockjax) {
  mockjax({
    url: '//server/otcs/cs/api/v1/contentauth?id=*',
    responseTime: 100,
    responseText: {
      "token": 'fsbbVDtk+v+FvdVId3rDZGQPFTS1eQ+nX4AFdqSnff8='
    }
  });
  mockjax({
    url: '//server/otcs/cs/api/v2/businessworkspaces/*/roles?fields=members',
    responseTime: 100,
    responseText: {
      "links": {
        "self": {
          "body": "",
          "content_type": "",
          "href": "/api/v2/businessworkspaces/*/roles?expand_members=true",
          "method": "GET",
          "name": ""
        }
      },
      "results": [
        {
          "actions": {
            "delete-role": {
              "body": "",
              "content_type": "",
              "form_href": "",
              "href": "/api/v2/businessworkspaces/13875/roles/63268",
              "method": "DELETE",
              "name": "Delete role"
            },
            "edit-role": {
              "body": "",
              "content_type": "",
              "form_href": "",
              "href": "/api/v2/businessworkspaces/13875/roles/63268",
              "method": "PUT",
              "name": "Edit role"
            }
          },
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "The manager is responsible for the location and the staff members.",
              "id": 63268,
              "inherited_from_id": 63269,
              "leader": true,
              "name": "Manager",
              "perms": 258207
            }
          }
        },
        {
          "actions": {
            "delete-role": {
              "body": "",
              "content_type": "",
              "form_href": "",
              "href": "/api/v2/businessworkspaces/13875/roles/63268",
              "method": "DELETE",
              "name": "Delete role"
            },
            "edit-role": {
              "body": "",
              "content_type": "",
              "form_href": "",
              "href": "/api/v2/businessworkspaces/13875/roles/63268",
              "method": "PUT",
              "name": "Edit role"
            }
          },
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              },
              {
                "business_email": "bspencer@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Bud Spencer",
                "first_name": "Bud",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 41158,
                "last_name": "Spencer",
                "middle_name": null,
                "name": "bspencer",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": null
              },
              {
                "business_email": null,
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Heinz Erhardt",
                "first_name": "Heinz",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 41268,
                "last_name": "Erhardt",
                "middle_name": null,
                "name": "herhardt",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": 63159
              },
              {
                "deleted": false,
                "display_name": "Famous Actors",
                "id": 63488,
                "leader_id": null,
                "name": "Famous Actors",
                "type": 1,
                "type_name": "Group"
              }
            ],
            "properties": {
              "description": "Every employee in the location has the staff role.",
              "id": 63269,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff",
              "perms": 233607
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 2",
              "id": 86259,
              "inherited_from_id": 86260,
              "leader": false,
              "name": "Staff Council 2",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 3",
              "id": 86260,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 3",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 4",
              "id": 86261,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 4",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 5",
              "id": 86262,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 5",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 6",
              "id": 86279,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 6",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 7",
              "id": 86263,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 7",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [],
            "properties": {
              "description": "",
              "display_name": "Staff Council 8",
              "id": 86264,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 8 ",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 9",
              "id": 86265,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 9",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 10",
              "id": 86266,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 10",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 11",
              "id": 86267,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 11",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 12",
              "id": 86268,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 12",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              },
              {
                "business_email": "bspencer@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Bud Spencer",
                "first_name": "Bud",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 41158,
                "last_name": "Spencer",
                "middle_name": null,
                "name": "bspencer",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": null
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 13",
              "id": 86269,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 13",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              },
              {
                "business_email": "bspencer@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Bud Spencer",
                "first_name": "Bud",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 41158,
                "last_name": "Spencer",
                "middle_name": null,
                "name": "bspencer",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": null
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 14",
              "id": 86270,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 14",
              "perms": 36995
            }
          }
        },
        {
          "actions": {},
          "data": {
            "members": [
              {
                "business_email": "lfunes@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Louis De Funes",
                "first_name": "Louis",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 39730,
                "last_name": "De Funes",
                "middle_name": null,
                "name": "lfunes",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": "images/louisdefunes.png"
              },
              {
                "business_email": "bspencer@elink.loc",
                "business_fax": null,
                "business_phone": null,
                "deleted": false,
                "display_name": "Bud Spencer",
                "first_name": "Bud",
                "group_id": 1001,
                "group_name": "DefaultGroup",
                "id": 41158,
                "last_name": "Spencer",
                "middle_name": null,
                "name": "bspencer",
                "office_location": null,
                "privilege_login": true,
                "privilege_modify_groups": false,
                "privilege_modify_users": false,
                "privilege_public_access": true,
                "privilege_system_admin_rights": false,
                "privilege_user_admin_rights": false,
                "time_zone": -1,
                "title": null,
                "type": 0,
                "type_name": "User",
                "photo_id": null
              }
            ],
            "properties": {
              "description": "",
              "display_name": "Staff Council 15",
              "id": 86271,
              "inherited_from_id": null,
              "leader": false,
              "name": "Staff Council 15",
              "perms": 36995
            }
          }
        }
      ]
    }
  });
  mockjax({
    url: '//server/otcs/cs/api/v1/members/41158?*',
    responseTime: 100,
    responseText: {
      "available_actions": [
        {
          "parameterless": true,
          "read_only": false,
          "type": "delete",
          "type_name": "Delete",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "create",
          "type_name": "Create",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "update",
          "type_name": "Update",
          "webnode_signature": null
        }
      ],
      "data": {
        "birth_date": null,
        "business_email": null,
        "cell_phone": null,
        "deleted": false,
        "display_name": "Bud Spencer",
        "first_name": "Bud",
        "gender": null,
        "group_id": 42144,
        "id": 41158,
        "last_name": "Spencer",
        "middle_name": null,
        "name": "bspencer",
        "office_location": "Kempten",
        "photo_url": null,
        "time_zone": null,
        "title": "System Engineer",
        "type": 0,
        "type_name": "User"
      },
      "type": 0,
      "type_name": "User"
    }
  });

  mockjax({
    url: '//server/otcs/cs/api/v1/members/63488?*',
    responseTime: 100,
    responseText: {
      "available_actions": [
        {
          "parameterless": true,
          "read_only": false,
          "type": "delete",
          "type_name": "Delete",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "create",
          "type_name": "Create",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "update",
          "type_name": "Update",
          "webnode_signature": null
        }
      ],
      "data": {
        "deleted": false,
        "display_name": "Famous Actors",
        "leader_id": null,
        "id": 63488,
        "name": "Famous Actors",
        "type": 1,
        "type_name": "Group"
      },
      "type": 1,
      "type_name": "Group"
    }
  });

  mockjax({
    url: '//server/otcs/cs/api/v1/members/41268?*',
    responseTime: 100,
    responseText: {
      "available_actions": [
        {
          "parameterless": true,
          "read_only": false,
          "type": "delete",
          "type_name": "Delete",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "create",
          "type_name": "Create",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "update",
          "type_name": "Update",
          "webnode_signature": null
        }
      ],
      "data": {
        "birth_date": null,
        "business_email": null,
        "cell_phone": null,
        "deleted": false,
        "display_name": "Heinz Erhardt",
        "first_name": "Heinz",
        "gender": null,
        "group_id": 42144,
        "id": 41268,
        "last_name": "Erhardt",
        "middle_name": null,
        "name": "herhardt",
        "office_location": "Kempten",
        "photo_url": null,
        "time_zone": null,
        "title": "System Engineer",
        "type": 0,
        "type_name": "User"
      },
      "type": 0,
      "type_name": "User"
    }
  });

  mockjax({
    url: '//server/otcs/cs/api/v1/members/39730?*',
    responseTime: 100,
    responseText: {
      "available_actions": [
        {
          "parameterless": true,
          "read_only": false,
          "type": "delete",
          "type_name": "Delete",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "create",
          "type_name": "Create",
          "webnode_signature": null
        },
        {
          "parameterless": false,
          "read_only": false,
          "type": "update",
          "type_name": "Update",
          "webnode_signature": null
        }
      ],
      "data": {
        "birth_date": null,
        "business_email": "lfunes@elink.lo",
        "cell_phone": null,
        "deleted": false,
        "display_name": "Louis De Funes",
        "first_name": "Louis",
        "gender": null,
        "group_id": 42144,
        "id": 39730,
        "last_name": "De Funes",
        "middle_name": null,
        "name": "lfunes",
        "office_location": "Kempten",
        "photo_url": null,
        "time_zone": null,
        "title": "System Engineer",
        "type": 0,
        "type_name": "User"
      },
      "type": 0,
      "type_name": "User"
    }
  });
  mockjax({
    url: '//server/otcs/cs/api/v2/businessworkspaces/*/roles/*',
    type: 'delete',
    responseTime: 100,
    contentType: 'text/json',
    status: 200,
    dataType: 'json',
    responseText: {}
  });

  mockjax({
    url: '//server/otcs/cs/api/v2/businessworkspaces/*/roles/*/members',
    type: 'post',
    responseTime: 100,
    contentType: 'text/json',
    status: 200,
    dataType: 'json',
    responseText: {
      success: true,
      data: 'Hello World'
    }
  });

  mockjax({
    url: '//server/otcs/cs/api/v2/businessworkspaces/*/roles/*/members/*',
    type: 'delete',
    responseTime: 100,
    contentType: 'text/json',
    status: 400,
    dataType: 'json',
    responseText: {
      success: true,
      data: 'Hello World'
    }
  });
  mockjax({
    url: '//server/otcs/cs/api/v2/businessworkspaces/*?metadata&fields=categories&include_icon=true',
    responseTime: 50,
    responseText: {
      "links": {
        "self": {
          "body": "",
          "content_type": "",
          "href": "/api/v2/businessworkspaces/*?metadata&fields=categories&include_icon=true",
          "method": "GET",
          "name": ""
        }
      },
      "results": {
        "actions": {
          "delete-icon": {
            "body": "",
            "content_type": "",
            "form_href": "",
            "href": "/api/v2/businessworkspaces/19598/icons",
            "method": "DELETE",
            "name": "Delete Icon"
          },
          "update-icon": {
            "body": "",
            "content_type": "",
            "form_href": "",
            "href": "/api/v2/businessworkspaces/19598/icons",
            "method": "PUT",
            "name": "Update Icon"
          },
          "upload-icon": {
            "body": "",
            "content_type": "",
            "form_href": "",
            "href": "/api/v2/businessworkspaces/19598/icons",
            "method": "POST",
            "name": "Upload Icon"
          }
        },
        "data": {
          "business_properties": {
            "has_default_display": true,
            "has_default_search": true,
            "isEarly": true,
            "workspace_type_id": 2,
            "workspace_type_name": "Equipment",
            "workspace_type_name_multilingual": {
              "de": "Ausrüstung",
              "en": "Equipment",
              "fr": "équipement"
            },
            "workspace_type_widget_icon_content": null
          },
          "properties": {
            "container": true,
            "container_size": 0,
            "create_date": "2015-04-20T09:20:56",
            "create_user_id": 1000,
            "description": "",
            "description_multilingual": {
              "en": ""
            },
            "guid": null,
            "icon": "/img11l/otsapxecm/otsapwksp_workspace_b8.png",
            "icon_large": "/img11l/otsapxecm/otsapwksp_workspace_b8_large.png",
            "id": 19598,
            "modify_date": "2015-04-21T13:09:18",
            "modify_user_id": 1000,
            "name": "Equipment Roller Support Stand",
            "name_multilingual": {
              "en": "Equipment Roller Support Stand"
            },
            "owner_group_id": 1001,
            "owner_user_id": 1000,
            "parent_id": 15419,
            "reserved": false,
            "reserved_date": null,
            "reserved_user_id": 0,
            "type": 848,
            "type_name": "Business Workspace",
            "versions_control_advanced": false,
            "volume_id": -2000,
            "workspace_type_id": 2,
            "workspace_type_name": "Equipment"
          },
          "categories": {
            "20368": {
              "20368_2": "image.png",
              "20368_3": "This all-purpose assistant helps you to saw large workpieces. Panels, large wooden boards and floorboards are easily placed on the stand, aligned on it and positioned against its stop. And the PTA 1000 weighs only about 6 kg, so it is just as easy to transport"
            },
            "23228": {
              "23228_18_1_19": "Bosch",
              "23228_18_1_20": "DE",
              "23228_18_1_21": "PTA 1000",
              "23228_18_1_22": "0603B05100",
              "23228_18_1_23": "3165140575775",
              "23228_18_1_24": 2015,
              "23228_18_1_25": 1,
              "23228_2_1_39": "2015-01-01T00:00:00",
              "23228_2_1_40": "2015-12-31T00:00:00",
              "23228_2_1_6": "WZG-001",
              "23228_2_1_7": "H",
              "23228_2_1_8": "The flexible PTA 1000. Perfect support when sawing large workpieces",
              "23228_2_1_9": null,
              "23228_3_1_10": "Wood",
              "23228_3_1_11": "Tools",
              "23228_3_1_12": null,
              "23228_3_1_13": "6,2",
              "23228_3_1_14": "kg",
              "23228_3_1_15": "700-1150mm",
              "23228_3_1_16": null,
              "23228_3_1_17": null,
              "23228_4_1_26": null,
              "23228_4_1_27": null,
              "23228_4_1_28": null,
              "23228_4_1_29": null,
              "23228_4_1_30": null,
              "23228_4_1_31": null,
              "23228_5_1_32": null,
              "23228_5_1_33": null,
              "23228_5_1_34": null,
              "23228_5_1_35": null,
              "23228_5_1_36": null,
              "23228_5_1_37": null,
              "23228_5_1_38": null
            }
          }
        },
        "metadata": {
          "properties": {
            "container": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "container",
              "multi_value": false,
              "name": "Container",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": 5,
              "type_name": "Boolean",
              "valid_values": [],
              "valid_values_name": []
            },
            "container_size": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "container_size",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Container Size",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "create_date": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "include_time": true,
              "key": "create_date",
              "multi_value": false,
              "name": "Created",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": -7,
              "type_name": "Date",
              "valid_values": [],
              "valid_values_name": []
            },
            "create_user_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "create_user_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Created By",
              "persona": "user",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "description": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "description",
              "max_length": null,
              "min_length": null,
              "multiline": true,
              "multilingual": true,
              "multi_value": false,
              "name": "Description",
              "password": false,
              "persona": "",
              "read_only": false,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            },
            "guid": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "guid",
              "multi_value": false,
              "name": "GUID",
              "persona": "",
              "read_only": false,
              "required": false,
              "type": -95,
              "type_name": "GUID",
              "valid_values": [],
              "valid_values_name": []
            },
            "icon": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "icon",
              "max_length": null,
              "min_length": null,
              "multiline": false,
              "multilingual": false,
              "multi_value": false,
              "name": "Icon",
              "password": false,
              "persona": "",
              "read_only": false,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            },
            "icon_large": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "icon_large",
              "max_length": null,
              "min_length": null,
              "multiline": false,
              "multilingual": false,
              "multi_value": false,
              "name": "Large Icon",
              "password": false,
              "persona": "",
              "read_only": false,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            },
            "id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "ID",
              "persona": "node",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "modify_date": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "include_time": true,
              "key": "modify_date",
              "multi_value": false,
              "name": "Modified",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": -7,
              "type_name": "Date",
              "valid_values": [],
              "valid_values_name": []
            },
            "modify_user_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "modify_user_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Modified By",
              "persona": "user",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "name": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "name",
              "max_length": null,
              "min_length": null,
              "multiline": false,
              "multilingual": true,
              "multi_value": false,
              "name": "Name",
              "password": false,
              "persona": "",
              "read_only": false,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            },
            "owner_group_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "owner_group_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Owned By",
              "persona": "group",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "owner_user_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "owner_user_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Owned By",
              "persona": "user",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "parent_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "parent_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Parent ID",
              "persona": "node",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "reserved": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "reserved",
              "multi_value": false,
              "name": "Reserved",
              "persona": "",
              "read_only": false,
              "required": false,
              "type": 5,
              "type_name": "Boolean",
              "valid_values": [],
              "valid_values_name": []
            },
            "reserved_date": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "include_time": true,
              "key": "reserved_date",
              "multi_value": false,
              "name": "Reserved",
              "persona": "",
              "read_only": false,
              "required": false,
              "type": -7,
              "type_name": "Date",
              "valid_values": [],
              "valid_values_name": []
            },
            "reserved_user_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "reserved_user_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Reserved By",
              "persona": "member",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "type": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "type",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Type",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "type_name": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "type_name",
              "max_length": null,
              "min_length": null,
              "multiline": false,
              "multilingual": false,
              "multi_value": false,
              "name": "Type",
              "password": false,
              "persona": "",
              "read_only": true,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            },
            "versions_control_advanced": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "versions_control_advanced",
              "multi_value": false,
              "name": "Versions Control Advanced",
              "persona": "",
              "read_only": false,
              "required": false,
              "type": 5,
              "type_name": "Boolean",
              "valid_values": [],
              "valid_values_name": []
            },
            "volume_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "volume_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "VolumeID",
              "persona": "node",
              "read_only": false,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "workspace_type_id": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "workspace_type_id",
              "max_value": null,
              "min_value": null,
              "multi_value": false,
              "name": "Workspace Type ID",
              "persona": "",
              "read_only": true,
              "required": false,
              "type": 2,
              "type_name": "Integer",
              "valid_values": [],
              "valid_values_name": []
            },
            "workspace_type_name": {
              "allow_undefined": false,
              "bulk_shared": false,
              "default_value": null,
              "description": null,
              "hidden": false,
              "key": "workspace_type_name",
              "max_length": null,
              "min_length": null,
              "multiline": false,
              "multilingual": false,
              "multi_value": false,
              "name": "Workspace Type",
              "password": false,
              "persona": "",
              "read_only": true,
              "regex": "",
              "required": false,
              "type": -1,
              "type_name": "String",
              "valid_values": [],
              "valid_values_name": []
            }
          },
          "categories": {
            "20368": {
              "20368": {
                "key": "20368",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Workspace Information",
                "next_id": 41,
                "persona": "category",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "20368_2": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "20368_2",
                "max_length": 240,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Image URL",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "20368_3": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "20368_3",
                "max_length": null,
                "min_length": null,
                "multiline": true,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Information",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              }
            },
            "23228": {
              "23228": {
                "key": "23228",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Equipment",
                "next_id": 41,
                "persona": "category",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_18": {
                "key": "23228_18",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Manufacturer",
                "next_id": null,
                "persona": "set",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_18_x_19": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_19",
                "max_length": 40,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Name",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_20": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_20",
                "max_length": 3,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Country",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_21": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_21",
                "max_length": 20,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Model Number",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_22": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_22",
                "max_length": 30,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Order Number",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_23": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_23",
                "max_length": 30,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Serial Number",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_24": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_24",
                "max_value": null,
                "min_value": null,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Construction Year",
                "persona": "",
                "read_only": false,
                "required": false,
                "type": 2,
                "type_name": "Integer",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_18_x_25": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_18_x_25",
                "max_value": null,
                "min_value": null,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Construction Month",
                "persona": "",
                "read_only": false,
                "required": false,
                "type": 2,
                "type_name": "Integer",
                "valid_values": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12
                ],
                "valid_values_name": []
              },
              "23228_2": {
                "key": "23228_2",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Master Data",
                "next_id": null,
                "persona": "set",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_2_x_39": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "include_time": false,
                "key": "23228_2_x_39",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Valid From",
                "persona": "",
                "read_only": false,
                "required": false,
                "type": -7,
                "type_name": "Date",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_2_x_40": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "include_time": false,
                "key": "23228_2_x_40",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Valid To",
                "persona": "",
                "read_only": false,
                "required": false,
                "type": -7,
                "type_name": "Date",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_2_x_6": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_2_x_6",
                "max_length": 18,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Equipment Number",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_2_x_7": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_2_x_7",
                "max_length": 1,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Category",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_2_x_8": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_2_x_8",
                "max_length": 80,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Description",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_2_x_9": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_2_x_9",
                "max_length": 40,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Status",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3": {
                "key": "23228_3",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "General",
                "next_id": null,
                "persona": "set",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_3_x_10": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_10",
                "max_length": 20,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Class",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_11": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_11",
                "max_length": 10,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Object Type",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_12": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_12",
                "max_length": 4,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Authorization Group",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_13": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_13",
                "max_length": 14,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Weight",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_14": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_14",
                "max_length": 3,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Weight Unit",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_15": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_15",
                "max_length": 30,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Size\\/Dimension",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_16": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_3_x_16",
                "max_length": 24,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Inventory Number",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_3_x_17": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "include_time": false,
                "key": "23228_3_x_17",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Start-up Date",
                "persona": "",
                "read_only": false,
                "required": false,
                "type": -7,
                "type_name": "Date",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4": {
                "key": "23228_4",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Location",
                "next_id": null,
                "persona": "set",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_4_x_26": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_26",
                "max_length": 4,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Maintenance Plant",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4_x_27": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_27",
                "max_length": 120,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Name",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4_x_28": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_28",
                "max_length": 80,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Street",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4_x_29": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_29",
                "max_length": 40,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "City",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4_x_30": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_30",
                "max_length": 10,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "City Postal Code",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_4_x_31": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_4_x_31",
                "max_length": 3,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Country Key",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5": {
                "key": "23228_5",
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Organization",
                "next_id": null,
                "persona": "set",
                "read_only": true,
                "required": false,
                "type": -18,
                "valid_values": []
              },
              "23228_5_x_32": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_32",
                "max_length": 4,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Company Code",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_33": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_33",
                "max_length": 4,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Business Area",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_34": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_34",
                "max_length": 16,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Asset",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_35": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_35",
                "max_length": 14,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Cost Center",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_36": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_36",
                "max_length": 4,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Planning Plant",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_37": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_37",
                "max_length": 3,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Planner Group",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              },
              "23228_5_x_38": {
                "allow_undefined": false,
                "bulk_shared": false,
                "default_value": null,
                "description": null,
                "hidden": false,
                "key": "23228_5_x_38",
                "max_length": 9,
                "min_length": null,
                "multiline": false,
                "multilingual": false,
                "multi_value": false,
                "multi_value_length_default": 1,
                "multi_value_length_fixed": true,
                "multi_value_length_max": 1,
                "name": "Catalog Profile",
                "password": false,
                "persona": "",
                "read_only": false,
                "regex": "",
                "required": false,
                "type": -1,
                "type_name": "String",
                "valid_values": [],
                "valid_values_name": []
              }
            }
          }
        },
        "metadata_order": {
          "properties": [
            "id",
            "type",
            "type_name",
            "name",
            "description",
            "parent_id",
            "volume_id",
            "guid",
            "create_date",
            "create_user_id",
            "modify_date",
            "modify_user_id",
            "owner_user_id",
            "owner_group_id",
            "reserved",
            "reserved_date",
            "reserved_user_id",
            "icon",
            "icon_large",
            "versions_control_advanced",
            "container",
            "container_size",
            "favorite"
          ]
        }
      }
    }
  });

});
