/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */


define({
  CommandNameEmail: 'Send e-mail',
  CommandNameExport: 'Download',
  CommandNameAddParticipant: 'Add participants',
  CommandNameExportParticipants: 'Download list of participants',
  CommandNamePrintParticipants: 'Print list of participants',
  CommandNameShowRoles: 'Show roles',
  CommandNameRemoveParticipant: 'Remove from team',
  CommandNameAddRole: 'Add role',
  CommandNameEditRole: 'Edit role',
  CommandNamePrintRoles: 'Print list of roles',
  CommandNameExportRoles: 'Download list of roles',
  CommandNameShowDetails: 'Show details',
  CommandNameDeleteRole: 'Delete',
  CommandNameAddConnectedWorkspace: 'Add business workspace',
  RemoveParticipantTitleSingle: 'Remove participant',
  RemoveParticipantTitleMultiple: 'Remove participants',
  RemoveParticipantMessage: 'Removing participants from the team will also remove them from their roles.',
  RemoveParticipantErrorMessageDefault: 'Cannot remove one or more participants.',
  DeleteRoleTitleSingle: 'Delete role',
  DeleteRoleTitleMultiple: 'Delete roles',
  DeleteRoleMessageNoParticipantsAffected: 'When you delete this role, no participant will be removed from the team: The role is empty or all participants of this role are members of other team roles.',
  DeleteRoleMessageParticipantsAffectedSingle: 'When you delete this role, 1 participant will be removed from the team.',
  DeleteRoleMessageParticipantsAffectedMultiple: 'When you delete this role, {0} participants will be removed from the team.',
  ErrorLoadingAddItemMenu: 'Cannot load workspace types to the Add menu.',
  AddConwsMetadataDialogTitle: 'Create {0}',
  BusinessWorkspace: 'business workspace',
  AddConwsMetadataDialogAddButtonTitle: 'Save',
  BusinessWorkspaceTypeName: 'Business Workspace',
  BusinessWorkspaceSuccessfullyCreated: '{0} was successfully created.',
  nameIsGeneratedAutomatically : 'Workspace name is generated automatically.',
  errorGettingCreateForm: 'Error getting form for workspace creation.',
  CommandNameAddCONWSTemplate: 'Add business workspace template',
  ErrorAddingSubfolderToNodesTable: 'Failed to add subfolder to the nodestable',

  CommandNameDeleteRelatedItem: 'Remove relationships',
  CommandVerbDeleteRelatedItem: 'remove',
  DeleteRelatedItemsNoneMessage: "No relationship removed.",
  DeleteOneRelatedItemSuccessMessage: "One relationship successfully removed.",
  DeleteSomeRelatedItemsSuccessMessage: "{0} relationships successfully removed.",
  DeleteManyRelatedItemsSuccessMessage: "{0} relationships successfully removed.",
  DeleteOneRelatedItemConfirmMessage: "Do you want to remove the relationship to '{1}'?",
  DeleteSomeRelatedItemsConfirmMessage: "Do you want to remove {0} relationships?",
  DeleteManyRelatedItemsConfirmMessage: "Do you want to remove {0} relationships?",

  CommandNameAddRelatedItem: 'Add relationships',
  CommandVerbAddRelatedItem: 'add',
  AddRelatedItemsNoneMessage: "No relationship added.",
  AddOneRelatedItemSuccessMessage: "One relationship successfully added.",
  AddSomeRelatedItemsSuccessMessage: "{0} relationships successfully added.",
  AddManyRelatedItemsSuccessMessage: "{0} relationships successfully added.",

  AddRoleSuccess: '{0} added successfully',
  EditRoleSuccess: '{0} updated successfully',
  BusinessWorkspaceRole: 'Business Workspace Role',
  DeletePermissionCommandForSubItems: 'Remove role',
  ToolbarItemEditRolePermission: 'Edit role permissions',
  DeleteRoleCommandSuccessMessage: "{0} was deleted successfully",
  DeleteRoleCommandFailMessage: "Failed to delete {0}."
});
