/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  ColumnMemberName2: "{1} {0}",
  ColumnMemberName3: "{1} {2} {0}",
  sizeInBytes: "{0} bytes",
  ErrorUnknown: "Unknown error.",
  InvalidResponse: "Invalid response received.",
  ErrorStatiNice: ["Confirm", "Error", "Warning", "Hint", "Information"],
  ErrorHtmlTpl: "<span class='msgIcon <%= statusPlain %>Icon'><%= statusNice %>: <%= msg %></span><br>",
  ErrorStringTpl: "<%= statusNice %>: <%= msg %>;\n",
  AuthenticationFailureDialogTitle: "Authentication failure",
  SessionExpiredDialogTitle: "Session expired",
  AuthenticationFailureDialogText: "The page will be reloaded and you may need to sign in again.",
  NodeTypeSearchQuery: 'Search',
  NodeTypeURL: 'Web address',
  NodeTypeAudio: 'Audio',
  NodeTypeCompressed: 'Compressed File',
  NodeTypeImage: 'Image',
  NodeTypeText: 'Text Document',
  NodeTypeHtml: 'Html Document',
  NodeTypeUnknown: 'Unknown',
  NodeTypeVideo: 'Video',
  NodeTypeDOC: 'Microsoft Word',
  NodeTypePDF: 'Portable Document Format',
  NodeTypePPT: 'Microsoft Powerpoint',
  NodeTypePresentation: 'Presentation',
  NodeTypeXLS: 'Microsoft Excel',
  NodeTypeSpreadsheet: 'Spreadsheet',
  NodeTypeFormula: 'Formula',
  NodeTypePublisher: 'Microsoft Publisher',
  NodeTypeVisio: 'Microsoft Visio',
  NodeTypeMPP: 'Microsoft Project',
  NodeTypeONE: 'Microsoft OneNote',

  NoConnectivity: "No connectivity",
  NetworkError: "Network communication failed.",
  resourceConflict: 'Due to an edit conflict, your changes could not be saved. Another user has changed the same object. Reload the page to reflect the latest changes.',
  Home: 'Home',
  Loading:"Loading...",
  NotAvailalbe:"Not available."

});
