/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  addTitle: 'Add',
  searchIconTooltip: 'Search by {0}',
  selectAll: 'Select all',
  selectAllTitle: 'Select all items',
  noResults: 'No item to display.',
  noSearchResults: 'No results found.',
  dragAndDropMessage: 'Drag and drop files here to add new content',
  items: 'Items',
  formatForNone: "{0} items",
  formatForOne: "{0} item",
  formatForTwo: "{0} items",
  formatForFive: "{0} items",
  asc_name: "Name (A-Z)",
  desc_name: "Name (Z-A)",
  asc_modify_date:"Modified (new-old)",
  desc_modify_date:"Modified (old-new)", 
  asc_size: "Size (small-large)",
  desc_size: "Size (large-small)",
  name: "Name",
  modified: "Modified",
  size: "Size",
  selectItem: 'Select {0}',
  selectItemAria: 'Select {0}. When selected an action bar of options can be reached per shift-tab',
  noPermissions: "You don't have permissions to add items to this location.",
  sortAscending: "Descending order - Click to sort ascending",
  sortAscendingAria: "{0} in descending order - Sort ascending",
  sortDescending: "Ascending order - Click to sort descending",
  sortDescendingAria: "{0} in ascending order - sort descending",
  sortBy: "Sort by",
  sortByAria: "Sort By menu - {0} selected"
});
