// Defines localizable strings in the default language (English)

csui.define({
  comments: 'Comments',
  viewprofile: 'View profile',
  unfollow: 'Unfollow',
  follow: 'Follow',
  chat: 'Chat',
  chatlabeltext: 'Chat with {0}',
  general: 'General',
  extended: 'Extended',
  personal: 'Personal',
  following: 'Following',
  followers: 'Followers',
  followingTooltip: 'Following {0}',
  followersTooltip: 'Followers {0}',
  activity: 'Activity',
  settings: 'Settings',
  notification: 'Notifications',
  notifyMentions: 'Notify me when I am mentioned',
  notifyNewFollower: 'Notify me when I have a new follower',
  notifyCommentsMyPosts: 'Notify me when someone comments on my content',
  notifyCommentsMyThreads: 'Notify me when someone comments on a thread I have participated in',
  notifyPrivateMessages: 'Notify me when I am sent a private message',
  privacySettings: 'Privacy settings for content messages',
  privacySettingsForStatusMessages: 'Privacy settings for status messages',
  privacyEveryOne: 'Everyone',
  privacyFollow: 'Only the people I follow',
  privacyNone: 'Only me',
  notifyMyUpdatesTo: 'Show my updates to:',
  myProfile: 'My profile',
  othersProfile: '{0}\'s profile',
  phone: 'Phone:',
  fax: 'Fax:',
  timezone: 'Time zone:',
  facebookLink: 'Facebook profile link',
  linkedinLink: 'Linkedin profile link',
  twitterLink: 'Twitter profile link',
  manager: 'Manager\'s name',
  defaultManagerMessage: 'Enter the name of your manager.',
  languagesSpoken: 'Languages spoken',
  aboutMe: 'About me',
  jobDescription: 'Job description',
  expertiseAreas: 'Areas of expertise',
  pastPositions: 'Past positions',
  degrees: 'Degrees / Certifications',
  awards: 'Awards / Honors',
  defaultLanguagesMessage: 'List the languages that you speak.',
  defaultAboutMeMessage: 'Write a brief description about yourself.',
  defaultfacebookMessage: 'Provide a link to your Facebook profile.',
  defaultLinkedInMessage: 'Provide a link to your LinkedIn profile.',
  defaulttwitterLinkMessage: 'Provide a link to your Twitter profile.',
  defaultJobDesc: 'Summarize your job responsibilities.',
  defaultExpertise: 'Describe your areas of expertise.',
  defaultPastPositions: 'List your relevant past positions.',
  defaultDegreeMessage: 'List your degrees or certifications.',
  defaultAwardMessage: 'List your awards or honors.',
  noFollowersMessage: 'List is empty. No one is following you',
  noFriendsMessage: 'You are not following anyone yet. To begin following, search for a user and, on their profile page, click Follow.',
  updatePic: 'Update picture',
  edit: 'Edit',
  update: 'Update',
  cancel: 'Cancel',
  more: 'more',
  less: 'less',
  userpickerplaceholder: 'Search Users',
  defaultErrorMessageForMiniProfilePopup: 'Server Error: Unable to display miniprofile',
  defaultErrorMessageForRelation: 'Server Error: Unable to perform operation',
  defaultErrorMessageForUpdateSettings: 'Server Error: Unable to update settings',
  defaultErrorMessageForUpdateExtentedField: 'Server Error: Unable to update field',
  defaultErrorMessageForUpdateExtentedLink: 'Server Error: Unable to update link',
  defaultErrorMessageForUserProfileActionLink: 'Server Error: Unable to follow/unfollow a deleted user',
  previous: 'Previous',
  next: 'Next',
  emoticon: 'Insert Emoji',
  defaultStatusPost: 'Post your status here',
  statusPost: 'My status',
  defaultErrorMessageForStatusPost: 'Server Error: Unable to post status',
  presenceTooltipTextFormat: '{0} {1}',
  presenceUnknownTooltipText: 'Unknown',
  presenceBeRightBackTooltipText: 'Be Right Back',
  presenceBusyTooltipText: 'Busy',
  presenceAwayTooltipText: 'Away',
  presenceOfflineTooltipText: 'Offline',
  presenceOnlineTooltipText: 'Online',
  presenceInaConferenceCallTooltipText: 'In a Conference Call',
  presencePresentingTooltipText: 'Presenting',
  presenceDoNotDisturbTooltipText: 'Do Not Disturb',
  presenceInaMeetingTooltipText: 'In a Meeting',
  presenceInaCallTooltipText: 'In a Call',
  presenceIdleOnlineTooltipText: 'Inactive',
  presenceIdleBusyTooltipText: 'Inactive Busy',
  presenceOutOfOfficeTooltipText: 'Out of Office',
  goBackTo: 'Go Back to',
  othersProfileTooltip: '\'{0}\'s\' profile',
  simpleUserProfileManagerLabel : 'Manager',
  simpleUserProfileOfficeLocation: 'Office location',
  simpleUserProfileEmail: 'Email',
  simpleUserProfileLabel: 'Update profile picture',
  simpleUserProfileMobile: 'Mobile',
  simpleUserProfilePhoneLabel: 'Phone',
  profile: 'Profile',
  uploadProfilePicture: 'Upload profile picture',
  deleteProfilePicture: 'Delete profile picture',
  dialogCloseButtonTooltip: 'Close',
  closeDialogLabel: 'Close Dialog',
  chatLabel: 'Chat',
  image: 'User Picker Image'
});
