/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
    dialogTitle: 'Business attachments',
    searchPlaceholder: 'Search %1',
    noResultsPlaceholder: 'No business attachments to display.',
    errorFieldFormatTagUnrecognized: 'Invalid format specification for {0}.',
    errorCustomColumnConfigInvalid: "Invalid custom column configuration: {0}.",
    errorCustomColumnMissingBraces: "Missing curly braces in custom column configuration: {0}.",
    errorOrderByMustNotBeString: "Configuration 'orderBy' must be an object not a string.",
    errorOrderByMissingBraces: "Missing curly braces in 'orderBy' configuration.",
    errorFilteringFailed: 'Filtering of result list failed. Please contact your administrator.',
    noAttachmentsFound: 'No business attachments found.',
    businessAttachments: 'Business attachments',
    CommandSnapshot: 'Snapshot',
    addBusinessAttachment: 'Add business attachment',
    fileSizeByte: "Bytes",
    fileSizeKByte: "KB",
    fileSizeMByte: "MB",
    parent_id: 'Location',
    reservedBy: 'Reserved by %1',
    snaphotCreated: 'Snapshot created',
    snaphotFailed: 'Snapshot creation failed',
    CommandDoneVerbCreated: 'created',
    fileSizeGByte: "GB",
    items: 'items',
    invalidConfigurationNoBusObjDisplay:'Cannot display business attachments because there is no business object defined.',
    invalidConfigurationNoBusObjConfigured:'No business object type configured for workspace display.',
    invalidConfigurationNoBusObjAvailable:'Cannot display business attachments because there is no business object available.',
    noBusinessObjectFound: 'No business object found',
    invalidConfiguration: 'Invalid widget configuration. Business object key, business object type and business application ID must be set.'
});
