/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */



define({
    dialogTitle: "Event Action Center",
    emptyListText: "No Events found.",
    ToolbarItemBack: "Back",
    ToolbarItemRefresh: "Refresh",
    ToolbarItemFilter: "Filter",
    actionPlan: "Action plan",
    addActionPlan: "Add action plan",
    columnEventName: "Event Name",
    columnSystemName: "System Name",
    columnActionPlan: "Action Plan",
    sourceLabel: "Source",
    rulesLabel: "Rules",
    runAs: "Run as",
    processMode: "Process mode",
    conjunctionAndLabel: "And",
    conjunctionOrLabel: "Or",
    operatorEqualtoLabel: "Equal to",
    operatorNotequaltoLabel: "Not equal to",
    synchronouslyProcessLabel: "Synchronously",
    asynchronouslyProcessLabel: "Asynchronously",
    csObjLabel: "Content Server object",
    evtPropLabel: "Event property",
    prevActLabel: "Result from previous action",
    labelExtendedECMVolume: "Extended ECM",
    saveLabel: "Save",
    cancelLabel: "Cancel",
    deleteActionPlanButton: "Delete",
    deleteActionPlanButtonAria: "Delete action plan",
    actionPlansGroup:"Action plans",
    backTitle: "Back",
    rulesTabLabel: "Rules",
    actionsTabLabel: "Actions",
    processModeTabLabel: "Process mode",
    rulesSetLegend: "Conditions",
    deleteActionPlanConfirmatonTitle: 'Delete action plan',
    deleteActionPlanConfirmatonText: 'Are you sure you want to delete {0}? ',
    newActionPlan: "New action plan",
    actionPlansListHeader: "Action plans",
    createLabel: "Create",
    closeLabel: "Close",
    genericWarningMsgOnDeletion: "Server Error: Unable to perform the action",
    warningMsgOnActionPlanNavigation: "All unsaved changes will be lost. Are you sure you want to continue?",
    actionPlanNavigationDialogTitle: "Unsaved changes",
    actionAttrParameterNameLabel: "Parameter name",
    actionAttrSourceLabel: "Source",
    actionAttrValueLabel: "Value"
});