// Defines localizable strings in the default language (English)

csui.define({
  comments: 'Comments',
  commentCount: 'comments',
  oneComment: 'comment',
  reply: 'Reply',
  replyCount: 'Reply ({0})',
  attachFile: 'Attach file',
  modifiedAt: 'Modified',
  update: 'Update',
  cancel: 'Cancel',
  commentBlank: '<strong>Oops.</strong> The comment field was blank.',
  post: 'Post',
  posting: 'Posting...',
  writeAComment: 'Write a comment',
  loadingComments: 'Loading comments...',
  deleteComment: 'Delete',
  edit: 'Edit',
  hide: 'Hide',
  confirmationText1: 'Are you sure that you want to delete this comment?',
  confirmationText2: 'All replies to the comment will also be deleted.',
  deleteCommentheader: 'Delete Comment',
  seeMoreReplies: 'Show more replies',
  fromContentServer: 'From Content Server',
  fromYourDesktop: 'From your desktop',
  attachmentPopoverTitle: 'Attachment',
  attachmentDeleteTitle: 'Delete Attachment',
  editAttachmentTitle: 'Edit Attachment',
  attachmentDeleteDescription: 'Are you sure you want to delete the attachment?',
  close: 'Close',
  uploadAttachment: 'Uploading Attachment',
  deleteReplyheader: 'Delete Reply',
  confirmationTextforReplyDelete: 'Are you sure that you want to delete this reply?',
  emoticon: 'Insert Emoji',
  errorOK: 'OK',
  Smile: 'Smile',
  Grin: 'Grin',
  Sad: 'Sad',
  Angry: 'Angry',
  Wink: 'Wink',
  Surprise: 'Surprise',
  Tounge: 'Tounge',
  Worried: 'Worried',
  Confused: 'Confused',
  RaisedEyebrow: 'Raised Eyebrow',
  Oops: 'Oops',
  ThumbsUp: 'Thumbs Up',
  ThumbsDown: 'Thumbs Down',
  Star: 'Star',
  Coffee: 'Coffee',
  Question: 'Question',
  Exclamation: 'Exclamation',
  targetPickerTitle: 'Select a Shortcut',
  versionMsg: "Added a new version ",
  version: "Version -",
  addMsg: "Added ",
  defaultErrorMessageForUpdateComment: 'Server Error: Unable to perform the action',
  defaultErrorMessageForUpdateWithAttachment: 'Server Error: Unable to perform the action',
  defaultErrorMessageForCreateRemoteObject: 'Server Error: Unable to perform the action',
  defaultErrorMessageForReply: 'Server Error: Unable to perform the action',
  defaultErrorMessageCommentsFetch: 'Server Error: Unable to perform the action',
  defaultErrorMessageUpdatePhoto: 'Server Error: Unable to perform photo update',
  defaultErrorMessageCommentSubmit: 'Server Error: Unable to post comment',
  more: 'more',
  less: 'less',
  noResults: 'No results found',
  itemNotExist: 'Sorry, the item you requested could not be accessed. Either it does not exist, or you do not have permission to access it. If you were sent a link to this item, please contact the sender for assistance.'
});
