/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  BytesOfSize: '{0} of {1}',
  UploadingItems: 'Uploading {0} items',
  UploadingOneItem: 'Uploading item',
  UploadingSomeItems: 'Uploading {0} items',
  UploadOneItemSuccessMessage: '"{0}" uploaded',
  UploadManyItemsSuccessMessage: "Uploaded {0} items",
  UploadOneItemFailMessage: '"{0}" failed to upload',
  UploadSomeItemsFailMessage: "{0} items failed to upload",
  UploadManyItemsFailMessage: "{0} items failed to upload",
  UploadSomeItemsFailMessage2: "{2} items failed to upload",   // {2} !!
  UploadManyItemsFailMessage2: "{2} items failed to upload",   // {2} !!
  UploadingSingleItem: 'Uploading "{0}"',
  FinalizingSingleItem: 'Finalizing "{0}"',
  UploadingOneItemStopped: '"{0}" stopped',
  UploadingAllItemsStopped: "{0} items stopped",
  UploadSomeItemsStopped: "Upload completed",
  State_pending: 'Waiting',
  State_processing: 'Processing',
  State_resolved: 'Done',
  State_rejected: 'Failed',
  State_aborted: 'Cancelled',
  State_stopped: 'Stopped',
  State_stopping: 'Stopping',
  State_finalizing: 'Finalizing',
  StateAction_pending: 'Waiting',
  StateAction_processing: 'Stop',
  StateAction_resolved: 'Done',
  StateAction_rejected: 'Done',
  StateAction_aborted: 'Done',
  Cancel: 'Cancel',
  CancelAria: 'Cancel upload of {0} item',
  StateAction_all_pending: 'Waiting for upload of all items',
  StateAction_all_processing: 'Stop upload of all items',
  StateAction_all_resolved: 'All items uploaded',
  StateAction_all_rejected: 'All items rejected to upload',
  StateAction_all_aborted: 'All items aborted to upload',
  Expand: 'Expand details',
  Collapse: 'Collapse details',
  Close: 'Close',
  CloseAria: 'Close the progress panel',
  minimize: 'Hide message banner ',
  minimizeAria: 'Hide message banner',
  UploadingLocation: 'Uploading to "{0}"',
  UploadedLocation: 'Uploaded to "{0}"',
  Retry: 'Retry',
  RetryAll: 'Retry all',
  GotoLocationLinkLabel: "Go to location"
});
