/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  ShortcutPickerTitle: "Select target for Shortcut",
  CommandNameAddItemMetadata: "Add Item with metadata",

  CommandNameAddVersion: "AddVersion",
  AddVersionNotAllowed : 'Unable to add version. Please try again when the current operation is finished',
  CommandTitleCopy: "Copy items",
  CommandNameCopy: "Copy",
  CommandVerbCopy: "copy",
  DialogTitleSingleCopy: "Copy {0} item",
  DialogTitleCopy: "Copy {0} items",
  SomeFilesNotCopiedSuccessfully: 'Some items were not successfully copied.',
  CopyingNodes: 'Copying {0} nodes',
  CopyingNode: 'Copying 1 node',
  CopyPageLeavingWarning: "If you leave the page now, pending items will not be copied.",
  CopyingOneItem: 'Copying "{0}"',
  CopyItems: 'Copying {0} items',
  CopySomeItems: 'Copying {0} items',
  CopyItemsNoneMessage: "No items copied.",
  CopyOneItemSuccessMessage: '"{0}" copied',
  CopySomeItemsSuccessMessage: '{0} items successfully copied.',
  CopyManyItemsSuccessMessage: '{0} items successfully copied.',
  CopyOneItemFailMessage: '"{0}" failed to copy',
  CopySomeItemsFailMessage: '{0} items failed to copy.',
  CopyManyItemsFailMessage: '{0} items failed to copy.',
  CopySomeItemsFailMessage2: '{2} items failed to copy.',    // {2} !!
  CopyManyItemsFailMessage2: '{2} items failed to copy.',    // {2} !!
  CopyingLocationLabel :  'Copying to "{0}"',
  CopiedLocationLabel : 'Copied to "{0}"',
  CopyNotAllowed : 'Unable to copy. Please try again when the current operation is finished',
  DeleteCommandConfirmDialogTitle: "Delete",
  DeleteCommandConfirmDialogHtml: "<span class='msgIcon WarningIcon'>" +
                                  "<%- message %>" +
                                  "</span>",
  DeleteCommandConfirmDialogSingleMessage: "Do you want to delete {0}?",
  DeleteCommandConfirmDialogMultipleMessage: "Do you want to delete {0} items?",
  CommandTitleDelete: "Delete items",
  CommandNameDelete: "Delete",
  CommandVerbDelete: "delete",
  DeletePageLeavingWarning: "If you leave the page now, pending items will not be deleted.",
  DeleteItemFailed: 'Deleting item {0} failed.',
  DeleteItems: 'Deleting {0} items',
  DeletingOneItem: 'Deleting "{0}"',
  DeletingSomeItems: 'Deleting {0} items',
  DeleteItemsNoneMessage: "No items deleted.",
  DeleteOneItemSuccessMessage: "'{0}' deleted.",
  DeleteSomeItemsSuccessMessage: "{0} items successfully deleted.",
  DeleteManyItemsSuccessMessage: "{0} items successfully deleted.",
  DeleteOneItemFailMessage: "'{0}' failed to delete.",
  DeleteSomeItemsFailMessage: "{0} items failed to delete.",
  DeleteManyItemsFailMessage: "{0} items failed to delete.",
  DeleteSomeItemsFailMessage2: "{2} items failed to delete.",   // {2} !!
  DeleteManyItemsFailMessage2: "{2} items failed to delete.",   // {2} !!
  deletingLocationLabel: 'Deleting from "{0}"',
  deletedLocationLabel: 'Deleted from "{0}"',
  DeleteNotAllowed : 'Unable to delete. Please try again when the current operation is finished',

  ApplyingManyItemsSuccessMessage: "Applied successfully to {0} items.",
  ApplyingOneItemFailMessage: "Failed to apply to 1 item.",
  ApplyingManyItemsFailMessage2: "Failed to apply to {0} items.",
  CommandNameDownload: "Download",
  CommandVerbDownload: "download",
  CommandNameZipDownload: "Download",
  CommandVerbZipDownload: "Download",
  VerifyZipAndDownloadPrefetch: "Verifying items",
  ExtractingZipAndDownload: "Extracting items",
  CompressingZipAndDownload: "Compressing items",
  CleanUpZipAndDownload: "Cleaning up",
  PreFlightDialogBtnContinue: "Continue",
  DownloadDialogBtnDownload: "Download",
  DialogBtnCancel: "Cancel",
  InvalidArchiveCharacters: "Special characters cannot be used in archive name: \\?:<>|\"\/@^,{}[]!%&()~'",
  InvalidArchiveName: "Invalid archive name.",
  TheArchiveNameCannotBeEmpty: "Archive name cannot be empty.",
  TheArchiveNameMaxLength: "Archive name is greater than the maximum length (248)",
  CommandTitleMove: "Move items",
  CommandNameMove: "Move",
  CommandNameVerbMove: "move",
  DialogTitleSingleMove: "Move {0} item",
  DialogTitleMove: "Move {0} items",
  SomeFilesNotMovedSuccessfully: 'Some items were not successfully moved.',
  MovePageLeavingWarning: "If you leave the page now, pending items will not be moved.",
  MovingNodes: 'Moving {0} nodes',
  MovingNode: 'Moving 1 node',
  MovingOneItem: 'Moving "{0}"',
  MovingItems: 'Moving {0} items',
  MovingSomeItems: 'Moving {0} items',
  MoveItemsNoneMessage: "No items moved.",
  MoveOneItemSuccessMessage: '"{0}" moved',
  MoveSomeItemsSuccessMessage: '{0} items successfully moved.',
  MoveManyItemsSuccessMessage: '{0} items successfully moved.',
  MoveOneItemFailMessage: '"{0}" failed to move',
  MoveSomeItemsFailMessage: '{0} items failed to move.',
  MoveManyItemsFailMessage: '{0} items failed to move.',
  MoveSomeItemsFailMessage2: '{2} items failed to move.',    // {2} !!
  MoveManyItemsFailMessage2: '{2} items failed to move.',    // {2} !!
  MovingLocationLabel :  'Moving to "{0}"',
  MovedLocationLabel : 'Moved to "{0}"',
  MoveNotAllowed : 'Unable to move. Please try again when the current operation is finished',
  CommandNamePaste: "Paste",
  CommandNameReserve: "Reserve",
  CommandVerbReserve: "reserve",
  ReservePageLeavingWarning: "If you leave the page now, pending items will not be reserved.",
  ReserveItemsNoneMessage: "No items reserved.",
  ReserveOneItemSuccessMessage: "1 item successfully reserved.",
  ReserveSomeItemsSuccessMessage: "{0} items successfully reserved.",
  ReserveManyItemsSuccessMessage: "{0} items successfully reserved.",
  ReserveOneItemFailMessage: "1 item failed to reserve.",
  ReserveSomeItemsFailMessage: "{0} items failed to reserve.",
  ReserveManyItemsFailMessage: "{0} items failed to reserve.",
  CommandNameFavorite: "Add Favorite",
  CommandVerbFavorite: "update Favorites",
  CommandDoneVerbFavorite: "added to Favorites",
  CommandRemovedVerbFavorite: "removed from Favorites",
  updateFavoriteFailTitle: "Update Favorite",
  updateFavoriteFailMessage: 'Failed to update Favorite for node "{0}". \n\n{1}',
  CommandDescriptionToggle: "Description Toggle",
  CommandHideDescription: "Hide description",
  CommandShowDescription: "Show description",
  CommandNameEmailLink: "Share",
  CommandVerbEmailLink: "share",
  EmailLinkSubject: 'I want to share the following links with you',
  EmailLinkDesktop: "Link for Desktop and Android",
  EmailAppleLinkFormat: "Link for iOS Mobile",
  EmailLinkCommandFailedWithTooMuchItemsErrorMessage: "Mail as link failed. Too many items were selected.",
  SignOutCommandName: "Sign Out",
  SwitchToClassicCommandName: "Classic View",
  CommandNameUnreserve: "Unreserve",
  CommandVerbUnreserve: "unreserve",
  UnreservePageLeavingWarning: "If you leave the page now, pending items will not be unreserved.",
  UnreserveItemsNoneMessage: "No items unreserved.",
  UnreserveOneItemSuccessMessage: "1 item successfully unreserved.",
  UnreserveSomeItemsSuccessMessage: "{0} items successfully unreserved.",
  UnreserveManyItemsSuccessMessage: "{0} items successfully unreserved.",
  UnreserveOneItemFailMessage: "1 item failed to unreserve.",
  UnreserveSomeItemsFailMessage: "{0} items failed to unreserve.",
  UnreserveManyItemsFailMessage: "{0} items failed to unreserve.",
  UserProfileCommandName: "Profile",
  CommandTitleUpload: "Upload documents",
  UploadNotAllowed : 'Unable to upload. Please try again when the current operation is finished',
  CommandVerbRename: "rename",
  CommandNameSaveFilter: "Save As",
  CommandVerbSaveFilter: "Save As",
  DialogTitleSaveFilter: "Save as",
  SaveFilterCommandSuccessfully: "{0} virtual folder created successfully.",
  NoEditUrl: 'Web page for editing of this doucment is not available.',
  CommandNameCopyLink: "Copy link",
  CommandVerbCopyLink: "copy link",
  CopyLinkSuccessMessage: "Link copied to clipboard.",
  CopyLinkFailMessage: "Copy link has failed to copy the link to clipboard.",
  DeletePermissionCommandRemoveOwner: "Remove owner",
  DeletePermissionCommandRemoveGroup: "Remove owner group",
  DeletePermissionCommandRemovePublicAccess: "Remove Public Access",
  DeletePermissionCommandRemoveOther: "Remove from list",
  DeletePermissionCommandConfirmDialogTitle: 'Remove {0}',
  DeletePermissionCommandConfirmDialogSingleMessage: 'Do you want to remove {0}' +
                                                     ' from this permissions list?',
  DeletePermissionCommandConfirmDialogPublicAccessMessage: 'Are you sure you want to remove' +
                                                           ' {0} from this permissions list?',
  DeletePermissionCommandSuccessMessage: "{0} was removed from the permissions list.",
  DeletePermissionCommandSuccessMessageWithCount: "{0} was removed from the permissions list of" +
                                                  " {1}.",
  DeletePermissionCommandFailMessage: "Failed to remove {0} from the permissions list.",
  publicAccess: 'Public Access',
  RestorePublicAccessSuccessMessage: "{0} restored",
  RestorePublicAccessSuccessMessageWithCount: "{0} restored to the permission list of {1}",
  undefinedCollection: 'Collection is undefined',
  EditPermissionCommandFailMessage: "Failed to edit {0} from the permissions list.",
  Owner: 'owner',

  CommandNameAddOwnerOrOwnerGroup: "Add Owner Or Owner Group",
  AddOwnerOrGroup: "Add owner or owner group",
  AddOwner: "Add owner",
  AddOwnerGroup: "Add owner group",
  CommandNameAddUserorGroup: 'Add user or group',
  CommandNameRestorePublicAccess: 'Restore public access',
  AddButtonLabel: 'Add',
  AddOwnerOrGroupDialogTitle: "Add Owner or Owner group",
  AddOwnerDialogTitle: "Add Owner",
  AddOwnerGroupDialogTitle: "Add Owner group",

  ChangeOwnerPermissionCommand: 'Change owner',
  ChangeOwnerGroupPermissionCommand: 'Change owner group',

  AddUserOrGroupSuccess: '{0} added successfully',
  AddUserOrGroupFailure: '{0} failed to add',
  AddUserOrGroupSuccessWithCount: '{0} was added to the permissions list of {1}.',

  formatForNone: "{0} items",
  formatForOne: "{0} item",
  formatForTwo: "{0} items",
  formatForFive: "{0} items",

  AppliedPermissions: 'Permissions applied selected item',
  AppliedPermissionsOneSuccess: 'Permissions applied to {0} item',
  AppliedPermissionsOnlySuccess: 'Permissions applied to {0} items',
  AppliedPermissionsOneFailure: 'Permissions failed to apply {0} item',
  AppliedPermissionsOnlyFailure: 'Permissions failed to apply {0} items',
  AppliedPermissionsSuccessAndFailure: 'Permissions applied to {0} items and failed to apply {1}' +
                                       ' items',
  CommandSuccessfullySingular: "{0} item successfully {1}.",
  CommandFailedSingular: "{0} item failed to {1}.",
  CommandSuccessfullyPlural: "{0} items successfully {1}.",
  CommandFailedPlural: "{0} items failed to {1}.",
  CommandFailedPartial: "{0} of {1} items failed to {2}.",

  NoConnectivity: "No connectivity",
  GoToOffline: "Go to offline files?",

  viewTypeUnsupported: 'This content type is not currently supported on a mobile device.',

  MobileIOS: "iOS Mobile",
  DesktopAndroid: "Desktop and Android",
  Close: 'Close',
  addButton: "Add",
  otheruser: "other user",
  addDocument: "Add Document",
  allUsersAndGroups: "Users and Groups",
  addUsersAndGroups: "Add users or groups",
  addGroups:"Add Groups",
  allGroups: "Groups",
  cancelButtonLabel: "Cancel",
  applyButtonLabel: "Apply",
  ThumbnailTitle: "Grid View",
  ListViewTitle: "Browse View",
  DensityLabel: "Density",
  error: "Error",
  EditPerspective: "Edit page",
  editPerspectiveErrorMessage: "The page cannot be edited. It is used as template for multiple pages",
  editPageDialogMessage: "Who will see the page edits?",
  editPageButton: "Everyone",
  personalizePageButton: "Only you",
  editPageCancelButton: "Cancel",
  editPageTitle: "Edit page",
  CreatePerspective: "Create new perspective",
  searchButtonMessage: "Search",
  personalizePage: "Personalize page",
});
