/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  properties: 'Properties',
  versions: 'Versions',
  general: 'General',
  UserPickerPlaceHolder: 'Enter name or group',
  PermissionLookupPlaceHolder: 'Enter name or group for permissions lookup',
  right_id: 'User / Group',
  permission_level: 'Permission level',
  goBackTooltip: 'Go back',
  emptyPermissionListMsg: "{0} was not found in this permissions list.",
  addMemberToGroup: "Add {0} as a member to a group that currently has permissions",
  grantAccessToMember: "Grant access to a group in which {0} is already a member",
  permissionLevelFullControl: "Full control",
  permissionLevelWrite: "Write",
  permissionLevelRead: "Read",
  permissionLevelCustom: "Custom...",
  permissionLevelNone: "None",

  FullControl: "Full control",
  Write: "Write",
  Read: "Read",
  Custom: "Custom",
  None: "None",
  see: "See",
  see_contents: "See contents",
  modify: "Modify",
  edit_attributes: "Edit attributes",
  add_items: "Add items",
  reserve: "Reserve",
  delete_versions: "Delete version",
  delete: "Delete",
  edit_permissions: "Edit permissions",
  edit_label_permissions: "edit_permissions",

  saveButtonLabel: "Ok",
  cancelButtonLabel: "Cancel",
  applyButtonLabel: "Apply",
  AddDropdownTitle: "Add",
  AddUserOrGroup: 'Add user or group',
  NoOwnerAssigned: "No owner assigned",
  addMajorVersion: "Add major version",
  allUsersAndGroups: "Users and Groups",
  addUsersAndGroups: "Add users or groups",
  addButtonLabel: 'Add',
  addButtonTooltip: 'Add member to group',
  cancelButtonTooltip: "Close dialog",
  noPermissionsAvailable: "Permissions page is not available for {0}",
});
