/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({

  ToolbarAria: 'Table toolbar',
  ToolbarItemFilter: 'Show filters',
  ToolbarItemFilterAria: 'Show filter panel',
  ToolbarItemOpen: 'Open',
  ToolbarItemDownload: 'Download',
  ToolbarItemBrowse: 'Browse',
  ToolbarItemCopy: 'Copy',
  ToolbarItemEmailLink: 'Mail as link',
  ToolbarItemEmailLinkShort: 'Mail as link',
  ToolbarItemPaste: 'Paste',
  ToolbarItemMove: 'Move',
  ToolbarItemShare: 'Share',
  ToolbarItemSendTo: 'Send to',
  ToolbarItemNavigate: 'Visit',
  ToolbarItemViewProperties: 'Properties',
  ToolbarItemVersionHistory: 'Version history',
  ToolbarItemDelete: 'Delete',
  ToolbarItemReserve: 'Reserve',
  ToolbarItemUnreserve: 'Unreserve',
  ToolbarItemEdit: 'Edit',
  ToolbarItemRename: 'Rename',
  ToolbarItemRenameFavorite: 'Rename Favorite',
  ToolbarItemOpenSavedQuery: 'Open',
  ToolbarItemExecuteSavedQuery: 'Execute',
  ToolbarItemInfo: 'Properties',
  ToolbarItemTimeline: 'Timeline',
  ToolbarItemToggleTableLayout: 'Toggle layout',
  ToolbarItemSettings: 'Settings',
  ToolbarItemAddFolder: 'Folder',
  ToolbarItemAddDocument: 'Document',
  ToolbarItemAdd: 'Add',
  ToolbarItemAddItem: 'Add Item',
  ToolbarItemAddVersion: 'Add version',
  ToolbarItemAddCategories: 'Add Categories',
  ToolbarItemMore: 'More actions',
  ToolbarItemPrint: 'Print',
  ToolbarItemOriginalEdit: 'Edit original',
  ToolbarItemOriginalShare: 'Share original',
  ToolbarItemOriginalReserve: 'Reserve original',
  ToolbarItemOriginalUnreserve: 'Unreserve original',
  ToolbarItemOriginalCopy: 'Copy original',
  ToolbarItemOriginalMove: 'Move original',
  ToolbarItemOriginalDownload: 'Download original',
  ToolbarItemOriginalDelete: 'Delete original',
  ToolbarItemCopyLink: 'Copy link',
  ToolbarItemOriginalCopyLink: 'Copy link original',
  ToolbarItemPermissions: 'View permissions',
  ToolbarItemDeletePermission: 'Remove from list',
  ToolbarItemEditPermission: 'Edit permissions',
  ToolbarItemApplyPermission: 'Apply permissions to sub-items',
  ToolbarItemChangeOwnerPermission: 'Change owner',
  ToolbarItemRemoveCollectionItems: 'Remove from collection',
  ToolbarItemInformation: 'Properties',
  ToolbarGoToLocation:'Go to location',
  ToolbarCollect:'Collect',
  ToolbarItemZipAndDownload: 'Download',
  MenuItemUploadFile: 'Upload file',
  MenuItemAddNewFolder: 'Add new Folder',
  MenuItemZipAndDownload: 'Download',
  MenuItemCopy: 'Copy',
  MenuItemMove: 'Move',
  MenuItemEmailLink: 'Email link',
  MenuItemShare: 'Share',
  MenuItemReserve: 'Reserve',
  MenuItemUnreserve: 'Unreserve',
  MenuItemDelete: 'Delete',
  MenuItemSendToDevice: 'Send to device',
  MenuItemRename: 'Rename',
  MenuItemTimeline: 'Timeline',
  MenuItemInformation: 'Properties',
  MenuItemCopyLink: 'Copy link',
  ToolbarItemComment: 'Comment',
  ToolbarItemShowDescription: 'Show description',
  ToolbarItemConfiguration: 'Configuration',
  ToolbarItemMaximizeWidgetView: 'Maximize widget view',
  ToolbarItemRestoreWidgetViewSize: 'Restore widget view size',

  AddUserOrGroups: 'Add user or groups',
  AddOwnerOrGroup: 'Add owner or owner group',
  RestorePublicAccess: 'Restore public access',
  AddToolbarItemsTitle: 'Add {0}',
  ToolbarItemThumbnail: "Grid view",
  ToolbarItemListView: "List view",
  ThumbnailTitle: "Grid view",
  ListViewTitle: "List view"
});
