/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  // english - English
  empty: "",
  required: "This field is required.",
  valid: "",
  invalid: "This field is invalid.",
  months: ["January", "February", "March", "April", "May", "June", "July", "August", "September",
    "October", "November", "December"],
  timeUnits: {
    SECOND: "seconds",
    MINUTE: "minutes",
    HOUR: "hours",
    DAY: "days",
    MONTH: "months",
    YEAR: "years"
  },
  notOptional: "This is a required field.",
  disallowValue: "{0} are disallowed values.",
  invalidValueOfEnum: "This field should have one of the values in {0}.  Current value is: {1}",
  notEnoughItems: "The minimum number of items is {0}",
  tooManyItems: "The maximum number of items is {0}",
  valueNotUnique: "Values must be unique.",
  notAnArray: "This value is not an Array",
  invalidDate: "Invalid date format.",
  invalidEmail: "Invalid Email format.",
  stringNotAnInteger: "This value must be an integer.",
  invalidIPv4: "Invalid IPv4 address. A valid format is 123.456.0.1",
  stringValueTooSmall: "The minimum value for this field is {0}.",
  stringValueTooLarge: "The maximum value for this field is {0}.",
  stringValueTooSmallExclusive: "Enter a value greater than {0}.",
  stringValueTooLargeExclusive: "Enter a value less than {0}.",
  stringDivisibleBy: "The value must be divisible by {0}.",
  stringNotANumber: "This value must be a number.",
  stringValueNotMultipleOf: "This value must be a multiple of {0}.",
  invalidPassword: "Invalid Password",
  invalidPhone: "Invalid Phone Number, e.g. (123) 456-9999",
  invalidPattern: "This field must have pattern {0}.",
  stringTooShort: "This field must contain at least {0} numbers or characters.",
  stringTooLong: "This field must not contain more than {0} characters",
  noneLabel: "None",
  addItemButtonLabel: "Add New Item",
  addButtonLabel: "Add",
  removeButtonLabel: "Remove",
  upButtonLabel: "Up",
  downButtonLabel: "Down",
  webAddressNeeded: "Web addess needs to be added."
})

