/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define(["csui/lib/underscore", "csui/lib/backbone"
], function (_, Backbone) {
	'use strict';

	function allOptionLabels() {
	}

	_.extend(allOptionLabels.prototype, Backbone.Events, {
		allSubtypeLabels: [
			"Accession Search",
			"Active Editing Sessions",
			"ActiveView",
			"Activity Manager",
			"Appearance",
			"Appearance Folder",
			"Appearance Workspace Folder",
			"Archived Document",
			"Backup Manager",
			"Backup Process",
			"Best Bets",
			"Binding",
			"Binding Folder",
			"Binding Volume",
			"Blog",
			"Blog Entry",
			"Blog Volume",
			"Categories Volume",
			"Category",
			"Category Folder",
			"Channel",
			"Channel Volume",
			"Classification",
			"Classification Shortcut",
			"Classification Tree",
			"Classification Volume",
			"Classified Items",
			"Collection",
			"Column",
			"Comm Expert Container",
			"Comm Expert Group",
			"Comm Store",
			"Comm URL Store",
			"Comm Workspace",
			"Comment Reply",
			"Comments",
			"Comments Associated Volume",
			"Comments Volume",
			"Community",
			"Community Template",
			"Community Template Folder",
			"Community Templates Volume",
			"Community Templates Volume",
			"Community Workspace",
			"Community XSL Volume",
			"Compound Document",
			"Compound Email",
			"Content Module Folder",
			"Content Move Job",
			"Content Move Job Folder",
			"Content Move Volume",
			"Content Server Appearances",
			"Content Server Applications",
			"Content Server Search Federator",
			"CS Application Manifest",
			"Custom View",
			"Custom View Template",
			"Data Flow Manager",
			"Data Source Folder",
			"Directory",
			"Directory Tree",
			"Directory Volume",
			"Directory Walker",
			"Discussion",
			"Discussion Volume",
			"Disposition Group",
			"Disposition Search",
			"Dispositions",
			"Document",
			"Document Conversion",
			"Document Conversion Server",
			"Domain Workspace",
			"Dynamic View",
			"E-Mail Message",
			"Email",
			"Email Folder",
			"Enterprise Extractor",
			"Enterprise Search Federator",
			"Enterprise Workspace",
			"Facet",
			"Facet Folder",
			"Facet Tree",
			"Facets Volume",
			"Failed Editing Sessions",
			"FAQ",
			"FAQ Entry",
			"Fixed System Column",
			"Folder",
			"Form",
			"Form Template",
			"Forum",
			"Forum Topics & Replies",
			"Front Porch",
			"Generation",
			"Global Appearance",
			"Global Content Server Sync Process",
			"Hold Group",
			"Hold Maintenance",
			"HTML View",
			"Importer",
			"Inbox",
			"Index Engine",
			"Index Tracer",
			"Internal OTDS",
			"Items in Email Conversation",
			"Journal Volume",
			"LiveReport",
			"Mail Store",
			"Mailbox",
			"Memcached Process",
			"Merge",
			"MicroPost",
			"Milestone",
			"My Personal Staging Folders",
			"My Projects",
			"My Reserved Items",
			"My Workbenches",
			"My Workspace",
			"Navigation Menu Volume",
			"News",
			"O365 Office Online Document",
			"O365 Office Online Volume",
			"Orphaned Items Volume",
			"Partition",
			"Partition Map",
			"Personal Community Workspace",
			"Personal Frontpage",
			"Personal Frontpage Volume",
			"Personal Staging Folder",
			"Personal Webpage",
			"Perspectives Volume",
			"Poll",
			"Process",
			"Process Folder",
			"Profile",
			"Project",
			"Project Template",
			"Project Workspace",
			"Prospector",
			"Prospector Queries",
			"Prospector Snapshot",
			"Provenance",
			"Proxy",
			"Pulse",
			"QAFolder",
			"Query File",
			"Question",
			"Question Reply",
			"Question Volume",
			"Recent Items",
			"Record Type",
			"Record Types",
			"Records Management Administration",
			"Records Management Workspace",
			"Recycle Bin",
			"Release",
			"Release Volume",
			"Remote Content Server",
			"Reply",
			"Reports",
			"Reports Volume",
			"Revision",
			"RM Classification",
			"RM Classification Terms",
			"RM Folder",
			"RM Part",
			"Search Enabled Hold",
			"Search Engine",
			"Search Form",
			"Search Manager",
			"Search Query",
			"Search Result Snapshot",
			"Search Results Template",
			"Shortcut",
			"Slice Folder",
			"Social Object Volume",
			"SocialObject",
			"Spider",
			"Submit Version",
			"System Volume",
			"Task",
			"Task Group",
			"Task List",
			"Task List Volume",
			"Tee",
			"Template Folder",
			"Template Folder",
			"Templates Volume",
			"Text Document",
			"Text Module",
			"Topic",
			"Tracer Volume",
			"Transport Item",
			"Transport Item Part",
			"Transport Package",
			"Transport Package Folder",
			"Transport Warehouse",
			"Update Distributor",
			"Urgent Request",
			"URL",
			"Virtual Folder",
			"Warehouse Folder",
			"Web Forms Connections",
			"Web Forms Database Connection",
			"Web Forms Database Lookup",
			"Web Forms Lookups",
			"WebReport",
			"Wiki",
			"Wiki Page",
			"Workbench",
			"Workflow Attachments",
			"Workflow Map",
			"Workflow Status",
			"Workflow Volume",
			"Workflows Edit Volume",
			"XML Activator Consumer",
			"XML Activator Producer",
			"XML DTD",
			"XML DTD Volume"
		]
	});

	allOptionLabels.prototype.get = Backbone.Model.prototype.get;
	_.extend(allOptionLabels, {version: "1.0"});

	return allOptionLabels;

});