/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  properties: 'Eigenschaften',
  versions: 'Versionen',
  general: 'Allgemein',
  MenuItemRename: 'Benennen',
  MenuItemEdit: 'Redigieren',
  MenuItemCopy: 'Kopie',
  MenuItemMove: 'Bewegen sich',
  MenuItemDownload: 'Download',
  MenuItemReserve: 'Reserve',
  MenuItemUnreserve: 'Reservierung aufheben',
  MenuItemAddVersion: 'In Version',
  MenuItemDelete: 'Löschen',
  addItemMetadataDialogButtonAddTitle: 'Hinzufügen',
  addItemMetadataDialogButtonCancelTitle: 'Abbrechen',
  addItemMetadataDialogTitle1: 'Neu: {0}',
  addItemMetadataDialogTitleGeneric: 'Objekt',
  addDocumentMetadataDialogTitle: 'Datei hochladen',
  addDocumentMetadataDialogAddButtonTitle: 'Hochladen',
  addItemPlaceHolderName: '{0} Name',
  editNameTooltip: 'Name ändern',
  cancelEditNameTooltip: 'Name ändern abbrechen',
  failedToSaveName: 'Fehler beim Namen zu speichern',
  failedToCreateItem: 'Es versaumt, die neuen Artikel zu erstellen',
  failedToValidateForms: 'Gescheitert, alle Formen zu validieren. Bitte überprüfen Sie, ob alle erforderlichen Felder eingetragen.',
  switchLanguageTooltip: 'Sprache wechseln',
  gotoPreviousCategoryTooltip: 'Vorherige Kategorie',
  gotoNextCategoryTooltip: 'Zeige nächste Kategorie',
  addNewProperties: 'Eigenschaften hinzufügen',
  addNewCategory: 'Neue Kategorie hinzufügen',
  addNewCategoryDialogTitle: 'Kategorie hinzufügen',
  addNewCategoryDialogAddButtonTitle: 'Hinzufügen',
  removeCategoryTooltip: 'Diese Kategorie entfernen',
  removeCategoryWarningTitle: 'Kategorie entfernen',
  removeCategoryWarningMessage: 'Wollen Sie wirklich, die Kategorie "{0}" entfernen?',
  removeCategoryFailMessageTitle: 'Entfernen der Kategorie fehlgeschlagen',
  removeCategoryFailMessage: 'Fehler beim entfernen der Kategorie "{0}". \n\n{1}',
  getCategoryFormsFailTitle: 'Kategorie Formulare laden',
  getCategoryFormsFailMessage: 'Fehler beim Laden der Kategorie Formulare für das Objekt "{0}". \n\n{1}',
  getCategoryActionsFailTitle: 'Kategorie Aktionen laden',
  getCategoryActionsFailMessage: 'Fehler beim Laden der Kategorie Aktionen für das Objekt "{0}". \n\n{1}',
  getActionsForACategoryFailMessage: 'Fehler beim Laden der Aktionen für Kategorie "{0}" für Objekt "{1}". \n\n{2}',
  addNewCategoryFailTitle: 'Kategorie zu Objekt hinzufugen',
  addNewCategoryFailMessage: 'Fehler beim Hinzufügen der Kategorie "{0}" zum Objekt "{1}". \n\n{2}',
  categoryExistsMessage: 'Fehler: Kategorie "{0}" ist bereits vorhanden.',
  loadNewCategoryFailTitle: 'Formular für Neue Kategorie',
  loadNewCategoryFailMessage: 'Fehler beim Formular für Kategorie "{0}" für Objekt "{1}" mit Node-ID "{2}". \n\n{3}',
  selectCategoryTitle: 'Wählen Sie eine Kategorie',
  selectCategoryButtonLabel: 'Hinzufügen',
  viewShortcutMessage: 'Verknüpfung anzeigen',
  viewOriginalMessage: 'Original anzeigen',
  shortcutLocationLabel: 'Original-Standort',
  closeMetadataButtonTooltip: 'Schließen Metadaten',
  formValidationErrorMessage: 'Erforderliche Felder müssen ausgefüllt werden',
  hideValidationErrorMessageIconTooltip: 'Ausblenden Validierungsfehler',
  missingRequiredMetadataForDocuments: 'Fehlende erforderlichen Metadaten aus irgendeinem Dokument (e).',
  goBackTooltip: 'geh zurück',
  onlyRequiredFieldsLabel: 'Nur erforderlich, Tags',
  defaultDialogTitle: 'Metadaten',
  defaultDialogOkButtonTitle: 'Ok',
  defaultDialogCancelButtonTitle: 'Absagen',
  moveOneItemMetadataDialogTitle: 'Verschieben Artikel',
  moveMultipleItemsMetadataDialogTitle: 'Bewegen Sie {0} Artikel',
  moveItemsMetadataDialogButtonTitle: 'Bewegen',
  copyOneItemMetadataDialogTitle: 'Artikel kopieren',
  copyMultipleItemsMetadataDialogTitle: 'Kopieren Sie {0} Artikel',
  copyItemsMetadataDialogButtonTitle: 'Kopieren',
  missingRequiredMetadataForObjects: 'Fehlende erforderlichen Metadaten für einige Objekt (e).',
  inheritanceOriginalProperties: 'mit ursprünglichen Eigenschaften',
  inheritanceDestinationProperties: 'mit Zieleigenschaften',
  inheritanceMergedProperties: 'mit kombinierten Eigenschaften',
  requiredTooltip: 'erforderlich',
  requiredPassedTooltip: 'Erforderliche Felder zufrieden',
  ToolbarItemVersionInfo: 'Eigenschaften',
  ToolbarItemVersionDelete: 'Löschen',
  ToolbarItemVersionPurgeAll: 'Alle vorherigen Versionen löschen',
  ToolbarItemVersionDownload: 'Herunterladen',
  versionColumnSizeTitle: 'Größe',
  versionColumnVersionNumberTitle: 'Versionen',
  openDoc: 'Öffnen',
  versionNumInBrowserTitle: 'Version {0}',
  formFieldSizeLabel: 'Größe',
  formFieldTypeLabel: 'Art',
  formFieldReservedStatusLabel: 'Reserviert Status',
  formFieldReservedByLabel: 'Reserviert durch',

  UrlLabel: 'Webadresse',
  UrlTitle: 'Webadresse',
  alpacaPlaceholderNotAvailable: 'n/a',
  alpacaPlaceholderUrl: 'In Web-Adresse',
  alpacaPlaceholderOTNodePicker: 'Objekt auswählen',
  alpacaPlaceholderDescription: 'Beschreibung hinzufügen',
  NoOwner: '<Kein Eigentümer>',
  showMore: 'Zeig mehr',
  collapse: 'Artikelliste ausblenden',
  expand: 'Artikelliste anzeigen'

});
