/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  months: ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"],
  dialogTitle: 'Workflow Tracking',
  emptyListText: 'There are no items to display',
  totalMsg: 'Total',
  onTime: 'On time',
  completed: 'Completed',
  late: 'Late',
  stopped: 'Stopped',
  expandLabel: 'Expand',
  dueDateLabel: 'Due date',
  currentStepNameLabel: 'Current step',
  assignedToLabel: 'Assigned to',
  startDateLabel: 'Start date',
  startedLabel: 'Started',
  workflowIDLabel: 'Workflow-ID',
  statusLabel:'Status',
  initiatorLabel:'Initiator',
  wfNameLabel: 'Workflow name',
  NameLabel:'Name',
  allFilterLabel: 'All',
  completedFilterLabel: 'Completed',
  stoppedFilterLabel: 'Stopped',
  lateFilterLabel: 'Late',
  ontimeFilterLabel: 'On Time',
  headerFilterTitle: 'Refine by',
  headerFilterLabel: 'Show items with status',
  days: 'days',
  day: 'day',
  on: 'on',
  dueInLabel: 'due in',
  dueLabel: 'due',
  todayLabel: 'today',
  details:'Details',
  attachments:'Attachments',
  startLabel: 'Start',
  endLabel: 'End',
  currentStepLabel: 'Current Step',
  nextStepLabel: 'Next Step',
  stoppedStepLabel: 'Stopped',
  completedStepLabel: 'Completed Step',
  currentStepsLabel: 'Current Steps',
  completedStepsLabel: 'Completed Steps',
  workflowStopDialogMessage: 'Are you sure you want to stop? A stopped Workflow cannot be resumed.',
  workflowStopDialogTitle: 'Stop Workflow',
  stoppedWorkflowMessage: 'One Workflow has been stopped.',
  stopActionLabel: 'Stop',
  deleteActionLabel: 'Delete',
  deleteWorkflowDialogTitle: 'Delete Workflow',
  deleteWorkflowDialogMessage: 'Are you sure you want to delete? This Workflow will be permanently deleted.',
  deletedWorkflowMessage: 'One Workflow has been deleted.',
  backgroundStepText: 'System Monitored',
  systemUserText: 'System'
});
