/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  dialogTitle: 'Favorites',
  deleteGroupConfirmatonTitle: 'Delete group',
  deleteGroupConfirmatonText: 'Are you sure you want to delete this group? All the favored items' +
                              ' in this group will also be deleted.',
  deleteGroupButtonLabel: 'Delete',
  deleteGroupButtonAria: 'Delete favorite group',
  emptyGroupText: 'Adding content to your Favorites list makes it a breeze to find.',
  editGroupButtonLabel: 'Edit',
  editGroupButtonAria: 'Edit favorite group name',
  errorFavoritesSaveFailed: 'Saving favorites failed.',
  errorFavoriteGroupSaveFailed: 'Saving favorites group failed.',
  favoriteColumnNameTitle: 'Favorite name',
  favoritesGroupAria: '{0}, Favorites Group',
  favoritesEmptyGroupAria: '{0}, Empty Favorites Group',
  favoriteGroupsNavAria: 'Favorites Groups',
  fav_ungrouped: 'Ungrouped',
  fav_ungroupedAria: 'Ungrouped favorites',
  groupAdd: 'Add group',
  groupAddButtonTitle: 'Add a new favorites group',
  groupHint1: 'To personalize the Favorites tile, you can push your favorite group to the top.',
  groupHint2: 'You can also re-order items within the groups, so that your most favorite items appear at the top of the Favorites tile.',
  addFav: 'Add Favorite',
  removeFav: 'Remove Favorite',
  updateFavoriteFailTitle: 'Update Favorite',
  updateFavoriteFailMessage: 'Failed to update favorite for node "{0}". \n\n{1}',
  addFavoriteNameLabel: 'Favorite name',
  addFavoriteNamePlaceHolder: 'Enter name',
  addFavoriteGroupLabel: 'Group',
  addFavoriteAddButtonLabel: 'Add',
  addFavoriteCancelButtonLabel: 'Cancel',
  addFavoriteCancelButtonAria: 'Cancel editing favorite group name',
  nameErrorMaxLengthExceed: 'Name cannot be longer than 248 characters.',
  nameErrorContainSemiColon: 'Name cannot contain a colon.',
  startEditMode: 'Edit',
  endEditMode: 'Done'
});
