/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  dialogTitle: "View role membership",
  missingConnector: 'Missing connector information!',
  AddRole: 'Add role',
  EditRole: 'Edit role',
  doneButtonLabel: 'Save',
  nextButtonLabel: 'Next',
  cancelButtonLabel: "Cancel",
  RoleStepName: 'Role',
  PermissionsStepName: 'Permissions',
  ParticipantsStepName: 'Participants',
  RoleName: 'Role name',
  RoleNamePlaceholder: 'Enter name',
  RoleDesc: 'Role Description',
  RoleDescPlaceholder: 'Add Description',
  TeamLead: 'Team Lead',
  SubItemsInherit: 'Apply to sub-items',
  backButtonTooltip: 'Go back',
  backButtonAria: 'Go back',
  selectPermissionLevel: 'Select permission level',
  simplePermissionSelection: 'Simple Permission Selection',
  rolePartcipantsWithNoparticipantsMessage: 'No participants have been added.',
  participantsTitle: 'Participants',
  addParticipantTitle: 'Add Participant',
  roleParticipantsUserPickerPlaceholder: 'Add participants',
  roleParticipantsDisabledMemberMessage: 'Is already a participant.',
  roleParticipantsSearchAria: 'Search for participants'
});
