csui.define({
  dialogTitle: 'Activity Feed',
  searchPlaceholder: 'Search in ActivityFeed',
  expandTitle:'Expand',

  // Note: use the exact 'column_key' for the client-side column titles
  name: "Step or task name",
  parent_id: "Workflow or task list name",
  versionMsg: "Added version ",
  modifiedAt: 'Modified',
  addMsg: "Added ",
  commentMsg: "Commented ",
  replyMsg: "Replied ",
  commentLabel: "Comment",
  status: "\u2019s status",
  version: "version",
  contentupdates: 'Content updates',
  statusupdates: 'Status updates',
  attributeupdates: 'Attribute updates',
  allusers: 'All users',
  iamfollowing: 'Users I am following',
  myfollowers: 'My followers',
  myupdates: 'My own updates',
  mentions: '@Mentions',
  myfavorites: 'My Favorites',
  activitytypes: 'Activity types',
  refineby: 'Refine by',
  updatesfrom: 'Updates from',
  allselectedlabel: 'Activity types (All)',
  emptyactivityfeed: "No activities found.",
  emptyactivityfeedforuserprofile: "No activities",
  more: "more",
  less: "less",
  comments: "Comments",
  newupdates: "New updates",
  statusfeed: "Status post",
  cancel: "Cancel",
  userProfileLink: "User Profile Link"
});
